<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 rel. 2 sp1 (x64) (http://www.altova.com) by Robert Ward (Ward Software Architects) -->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <wsdl:import namespace="http://epri.com/powergeneration/2020/NuclearGenerationStationsWsdl" location="Water_Chemistry/WSDLs/NuclearGenerationStations.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/NuclearGenerationUnitCyclesWsdl" location="Water_Chemistry/WSDLs/NuclearGenerationUnitCycles.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/NuclearGenerationUnitOutagesWsdl" location="Water_Chemistry/WSDLs/NuclearGenerationUnitOutages.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/PWRNuclearGenerationUnitsWsdl" location="Water_Chemistry/WSDLs/PWRNuclearGenerationUnits.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/PWRWaterChemistryDataSetsWsdl" location="Water_Chemistry/WSDLs/PWRWaterChemistryDataSets.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/GrossGeneratorActivePowerOutputMeasurementsWsdl" location="Heat_Transfer/WSDLs/GrossGeneratorActivePowerOutputMeasurements.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/GrossGeneratorPowerOutputMeasurementsWsdl" location="Heat_Transfer/WSDLs/GrossGeneratorPowerOutputMeasurements.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/GrossGeneratorReactivePowerOutputMeasurementsWsdl" location="Heat_Transfer/WSDLs/GrossGeneratorReactivePowerOutputMeasurements.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/SteamGenerationSystemBlowdownFlowMeasurementsWsdl" location="Heat_Transfer/WSDLs/SteamGenerationSystemBlowdownFlowMeasurements.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/SteamGenerationSystemEnergyOutputMeasurementsWsdl" location="Heat_Transfer/WSDLs/SteamGenerationSystemEnergyOutputMeasurements.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/SteamGenerationSystemOutputMassFlowMeasurementsWsdl" location="Heat_Transfer/WSDLs/SteamGenerationSystemOutputMassFlowMeasurements.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/SteamGenerationSystemOutputPressureMeasurementsWsdl" location="Heat_Transfer/WSDLs/SteamGenerationSystemOutputPressureMeasurements.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/SteamGenerationSystemOutputTemperatureMeasurementsWsdl" location="Heat_Transfer/WSDLs/SteamGenerationSystemOutputTemperatureMeasurements.wsdl"/>
    <wsdl:import namespace="http://epri.com/powergeneration/2020/MaintenanceOrdersWsdl" location="Maintenance_Orders/WSDLs/MaintenanceOrders.wsdl"/>
</wsdl:definitions>
